cd disable-community-survey
sh enable_feature.sh
cd ..
cd hajtex-branding
sh enable_feature.sh
cd ..
cd login-page
sh enable_feature.sh
cd ..
cd oidc
sh enable_feature.sh
cd ..
cd references
sh enable_feature.sh
cd ..
cd registration-page
sh enable_feature.sh
cd ..
cd shell-escape
sh enable_feature.sh
cd ..
cd symbol-palette
sh enable_feature.sh
cd ..
cd track-changes
sh enable_feature.sh
cd ..
